# Generated by Django 2.2.5 on 2019-12-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_hospital_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_profile',
        ),
        migrations.CreateModel(
            name='Appointment_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=128)),
                ('patient_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField()),
                ('hospital_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital_app.Hospital_list')),
            ],
        ),
    ]
