# Generated by Django 2.2.5 on 2019-12-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_auto_20191223_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('age', models.IntegerField(max_length=128)),
                ('sex', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField()),
                ('phone', models.IntegerField(max_length=128)),
                ('street_address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
